name: flutter_project_12
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  flex_color_picker: ^3.3.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  get_it: ^8.0.3
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

